"""v7 renaming4

Revision ID: 722a2aa39a1d
Revises: eac40e21aef7
Create Date: 2019-08-06 15:08:25.470629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '722a2aa39a1d'
down_revision = 'eac40e21aef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Daily', sa.Column('act_work_pay', sa.Integer(), nullable=True))
    op.add_column('Daily', sa.Column('cont_work_pay', sa.Integer(), nullable=True))
    op.drop_column('Daily', 'cwork_pay')
    op.drop_column('Daily', 'awork_pay')
    op.add_column('Monthly', sa.Column('act_work_mpay', sa.Integer(), nullable=True))
    op.add_column('Monthly', sa.Column('cont_work_mpay', sa.Integer(), nullable=True))
    op.drop_constraint('monthly_ibfk_1', 'Monthly', type_='foreignkey')
    op.create_foreign_key(None, 'Monthly', 'WorkContract', ['cont_id'], ['cont_id'])
    op.drop_column('Monthly', 'awork_mpay')
    op.drop_column('Monthly', 'cwork_mpay')
    op.drop_constraint('weekly_ibfk_1', 'Weekly', type_='foreignkey')
    op.create_foreign_key(None, 'Weekly', 'WorkContract', ['cont_id'], ['cont_id'])
    op.drop_constraint('workcondition_ibfk_1', 'WorkCondition', type_='foreignkey')
    op.create_foreign_key(None, 'WorkCondition', 'WorkContract', ['cont_id'], ['cont_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint('workcontract_ibfk_2', 'WorkContract', type_='foreignkey')
    op.drop_constraint('workcontract_ibfk_1', 'WorkContract', type_='foreignkey')
    op.create_foreign_key(None, 'WorkContract', 'WorkPlace', ['wp_id'], ['wp_id'])
    op.create_foreign_key(None, 'WorkContract', 'User', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'WorkContract', type_='foreignkey')
    op.drop_constraint(None, 'WorkContract', type_='foreignkey')
    op.create_foreign_key('workcontract_ibfk_1', 'WorkContract', 'workplace', ['wp_id'], ['wp_id'])
    op.create_foreign_key('workcontract_ibfk_2', 'WorkContract', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'WorkCondition', type_='foreignkey')
    op.create_foreign_key('workcondition_ibfk_1', 'WorkCondition', 'workcontract', ['cont_id'], ['cont_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'Weekly', type_='foreignkey')
    op.create_foreign_key('weekly_ibfk_1', 'Weekly', 'workcontract', ['cont_id'], ['cont_id'])
    op.add_column('Monthly', sa.Column('cwork_mpay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('Monthly', sa.Column('awork_mpay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Monthly', type_='foreignkey')
    op.create_foreign_key('monthly_ibfk_1', 'Monthly', 'workcontract', ['cont_id'], ['cont_id'])
    op.drop_column('Monthly', 'cont_work_mpay')
    op.drop_column('Monthly', 'act_work_mpay')
    op.add_column('Daily', sa.Column('awork_pay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('Daily', sa.Column('cwork_pay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('Daily', 'cont_work_pay')
    op.drop_column('Daily', 'act_work_pay')
    # ### end Alembic commands ###
