"""v7 renaming5

Revision ID: e10f46a561f5
Revises: 722a2aa39a1d
Create Date: 2019-08-06 15:48:11.004596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e10f46a561f5'
down_revision = '722a2aa39a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Daily', sa.Column('daily_id', sa.String(length=50), nullable=False))
    op.drop_column('Daily', 'daliy_id')
    op.drop_constraint('monthly_ibfk_1', 'Monthly', type_='foreignkey')
    op.create_foreign_key(None, 'Monthly', 'WorkContract', ['cont_id'], ['cont_id'])
    op.drop_constraint('weekly_ibfk_1', 'Weekly', type_='foreignkey')
    op.create_foreign_key(None, 'Weekly', 'WorkContract', ['cont_id'], ['cont_id'])
    op.drop_constraint('workcondition_ibfk_1', 'WorkCondition', type_='foreignkey')
    op.create_foreign_key(None, 'WorkCondition', 'WorkContract', ['cont_id'], ['cont_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint('workcontract_ibfk_1', 'WorkContract', type_='foreignkey')
    op.drop_constraint('workcontract_ibfk_2', 'WorkContract', type_='foreignkey')
    op.create_foreign_key(None, 'WorkContract', 'WorkPlace', ['wp_id'], ['wp_id'])
    op.create_foreign_key(None, 'WorkContract', 'User', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'WorkContract', type_='foreignkey')
    op.drop_constraint(None, 'WorkContract', type_='foreignkey')
    op.create_foreign_key('workcontract_ibfk_2', 'WorkContract', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('workcontract_ibfk_1', 'WorkContract', 'workplace', ['wp_id'], ['wp_id'])
    op.drop_constraint(None, 'WorkCondition', type_='foreignkey')
    op.create_foreign_key('workcondition_ibfk_1', 'WorkCondition', 'workcontract', ['cont_id'], ['cont_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'Weekly', type_='foreignkey')
    op.create_foreign_key('weekly_ibfk_1', 'Weekly', 'workcontract', ['cont_id'], ['cont_id'])
    op.drop_constraint(None, 'Monthly', type_='foreignkey')
    op.create_foreign_key('monthly_ibfk_1', 'Monthly', 'workcontract', ['cont_id'], ['cont_id'])
    op.add_column('Daily', sa.Column('daliy_id', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('Daily', 'daily_id')
    # ### end Alembic commands ###
