"""v7 renaming3

Revision ID: eac40e21aef7
Revises: 6bee4ad4b906
Create Date: 2019-08-06 15:06:55.327806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eac40e21aef7'
down_revision = '6bee4ad4b906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Daily', sa.Column('act_rest_time', sa.Time(), nullable=True))
    op.add_column('Daily', sa.Column('act_work_time', sa.Time(), nullable=True))
    op.add_column('Daily', sa.Column('cont_rest_time', sa.Time(), nullable=True))
    op.add_column('Daily', sa.Column('cont_work_time', sa.Time(), nullable=True))
    op.drop_column('Daily', 'cwork_time')
    op.drop_column('Daily', 'arest_time')
    op.drop_column('Daily', 'crest_time')
    op.drop_column('Daily', 'awork_time')
    op.add_column('Monthly', sa.Column('act_rest_mtime', sa.Time(), nullable=True))
    op.add_column('Monthly', sa.Column('act_work_mtime', sa.Time(), nullable=True))
    op.add_column('Monthly', sa.Column('cont_rest_mtime', sa.Time(), nullable=True))
    op.add_column('Monthly', sa.Column('cont_work_mtime', sa.Time(), nullable=True))
    op.drop_constraint('monthly_ibfk_1', 'Monthly', type_='foreignkey')
    op.create_foreign_key(None, 'Monthly', 'WorkContract', ['cont_id'], ['cont_id'])
    op.drop_column('Monthly', 'arest_mtime')
    op.drop_column('Monthly', 'cwork_mtime')
    op.drop_column('Monthly', 'awork_mtime')
    op.drop_column('Monthly', 'crest_mtime')
    op.drop_constraint('weekly_ibfk_1', 'Weekly', type_='foreignkey')
    op.create_foreign_key(None, 'Weekly', 'WorkContract', ['cont_id'], ['cont_id'])
    op.drop_constraint('workcondition_ibfk_1', 'WorkCondition', type_='foreignkey')
    op.create_foreign_key(None, 'WorkCondition', 'WorkContract', ['cont_id'], ['cont_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint('workcontract_ibfk_2', 'WorkContract', type_='foreignkey')
    op.drop_constraint('workcontract_ibfk_1', 'WorkContract', type_='foreignkey')
    op.create_foreign_key(None, 'WorkContract', 'WorkPlace', ['wp_id'], ['wp_id'])
    op.create_foreign_key(None, 'WorkContract', 'User', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'WorkContract', type_='foreignkey')
    op.drop_constraint(None, 'WorkContract', type_='foreignkey')
    op.create_foreign_key('workcontract_ibfk_1', 'WorkContract', 'workplace', ['wp_id'], ['wp_id'])
    op.create_foreign_key('workcontract_ibfk_2', 'WorkContract', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'WorkCondition', type_='foreignkey')
    op.create_foreign_key('workcondition_ibfk_1', 'WorkCondition', 'workcontract', ['cont_id'], ['cont_id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'Weekly', type_='foreignkey')
    op.create_foreign_key('weekly_ibfk_1', 'Weekly', 'workcontract', ['cont_id'], ['cont_id'])
    op.add_column('Monthly', sa.Column('crest_mtime', mysql.TIME(), nullable=True))
    op.add_column('Monthly', sa.Column('awork_mtime', mysql.TIME(), nullable=True))
    op.add_column('Monthly', sa.Column('cwork_mtime', mysql.TIME(), nullable=True))
    op.add_column('Monthly', sa.Column('arest_mtime', mysql.TIME(), nullable=True))
    op.drop_constraint(None, 'Monthly', type_='foreignkey')
    op.create_foreign_key('monthly_ibfk_1', 'Monthly', 'workcontract', ['cont_id'], ['cont_id'])
    op.drop_column('Monthly', 'cont_work_mtime')
    op.drop_column('Monthly', 'cont_rest_mtime')
    op.drop_column('Monthly', 'act_work_mtime')
    op.drop_column('Monthly', 'act_rest_mtime')
    op.add_column('Daily', sa.Column('awork_time', mysql.TIME(), nullable=True))
    op.add_column('Daily', sa.Column('crest_time', mysql.TIME(), nullable=True))
    op.add_column('Daily', sa.Column('arest_time', mysql.TIME(), nullable=True))
    op.add_column('Daily', sa.Column('cwork_time', mysql.TIME(), nullable=True))
    op.drop_column('Daily', 'cont_work_time')
    op.drop_column('Daily', 'cont_rest_time')
    op.drop_column('Daily', 'act_work_time')
    op.drop_column('Daily', 'act_rest_time')
    # ### end Alembic commands ###
